version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "JDFlynn1985"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
