'use client';

/**
 * @fileOverview API Documentation portal using Swagger UI.
 * Relocated to /api/v1/api-docs for versioned grouping.
 * Provides interactive exploration of the Scholarly Research API.
 * Consumes the dynamic /api/doc endpoint generated by next-swagger-doc.
 */

import dynamic from 'next/dynamic';
import 'swagger-ui-react/swagger-ui.css';
import { Button } from '@/components/ui/button';
import { ArrowLeft, BookOpen, ShieldCheck, ExternalLink } from 'lucide-react';
import Link from 'next/link';

// SwaggerUI does not support SSR out of the box
const SwaggerUI = dynamic(() => import('swagger-ui-react'), { 
  ssr: false,
  loading: () => (
    <div className="p-20 text-center animate-pulse space-y-4">
      <div className="h-10 w-64 bg-muted rounded mx-auto" />
      <div className="h-4 w-48 bg-muted rounded mx-auto" />
      <p className="text-muted-foreground">Initializing Scholarly Documentation Engine...</p>
    </div>
  )
});

export default function ApiDocs() {
  return (
    <div className="min-h-screen bg-background">
      <header className="bg-primary text-primary-foreground p-6 shadow-md">
        <div className="container max-w-6xl mx-auto flex justify-between items-center">
          <div className="flex items-center gap-4">
            <Link href="/">
              <Button variant="ghost" size="icon" className="text-primary-foreground hover:bg-white/10 rounded-full">
                <ArrowLeft className="h-5 w-5" />
              </Button>
            </Link>
            <div>
              <h1 className="text-2xl font-bold font-headline flex items-center gap-2">
                <BookOpen className="h-6 w-6 text-accent" /> API Documentation
              </h1>
              <p className="text-xs text-primary-foreground/70">Interactive Scholarly Integration Guide (v1)</p>
            </div>
          </div>
          <div className="hidden md:flex items-center gap-3">
             <Button variant="outline" size="sm" className="bg-white/10 border-white/20 text-white hover:bg-white/20" asChild>
                <Link href="/api-keys">
                   Get lv_token <ExternalLink className="ml-2 h-3 w-3" />
                </Link>
             </Button>
             <div className="flex items-center gap-2 bg-accent/20 px-4 py-2 rounded-full text-xs font-bold text-accent">
               <ShieldCheck className="h-4 w-4" />
               v1.0.0 (OpenAPI 3.0)
             </div>
          </div>
        </div>
      </header>

      <main className="container max-w-6xl mx-auto py-8">
        <div className="bg-card rounded-xl border shadow-xl overflow-hidden min-h-[70vh]">
          {/* Point to the dynamic Swagger spec endpoint */}
          <SwaggerUI url="/api/doc" />
        </div>
      </main>

      <footer className="container max-w-6xl mx-auto py-12 text-center space-y-4">
        <div className="flex justify-center gap-6 text-xs font-medium text-muted-foreground uppercase tracking-widest">
           <Link href="/terms" className="hover:text-primary">Terms of Use</Link>
           <Link href="/privacy" className="hover:text-primary">Privacy Policy</Link>
           <Link href="mailto:engineering@lexiverse.app" className="hover:text-primary">Support</Link>
        </div>
        <p className="text-[10px] text-muted-foreground">
          © 2024 LexiVerse Explorer. Dedicated to the advancement of theological research through technology.
        </p>
      </footer>
    </div>
  );
}
